### ISSUE TITLE
UI android mobile issue:-  helpline text is coming out of input box(Check screenshot)

### ISSUE THREAD

**Issue by ArjitRout** [nic-delhi/AarogyaSetu_Android#126] opened 2020-05-27 06:07 UTC
![text_coming_outofbox](https://user-images.githubusercontent.com/37146364/82984156-2ab9e180-a00f-11ea-8db4-dc4ea96130fc.JPG)

![EE4C8828-27A1-4A25-8B6B-7EE04218D2DB_1_105_c](https://user-images.githubusercontent.com/37146364/82985265-576ef880-a011-11ea-9c26-2639bac79f8d.jpeg)

Language used:- Odia
Scenario:- After completing the setup this issue will come(In split mode of application and normal full screen)

**Comment by ayushashi11** [comment] 2020-05-27 06:12
Same issue while using
Kannad, Telugu, Tamil, Malayalam, Bangla and Assamese

**Comment by aravindvnair99** [comment] 2020-05-28 17:51
@ArjitRout Please check for existing issues before opening a new one. You can close this and proceed there. Duplicate of #7

**Closed** 2020-07-18 19:53 UTC
