### ISSUE TITLE
The FAB (Floating Action Button) image in chat session is not loading

### ISSUE THREAD

**Issue by Demon-stare** [nic-delhi/AarogyaSetu_Android#291] opened 2020-05-28 14:52 UTC

**Comment by sreejeet** [comment] 2020-05-28 14:54
I think it is a Duplicate of #7.
Please close this if it is a duplicate.
Else provide more details so developers can debug faster.

**Comment by Demon-stare** [comment] 2020-05-28 14:56
Yes sorry closing it in 3...2...1..

**Closed** 2020-05-28 14:56 UTC
