### ISSUE TITLE
Addition of information about zones and displaying of the info in radius sections.

### ISSUE THREAD

**Issue by arav09** [nic-delhi/AarogyaSetu_Android#328] opened 2020-05-29 12:50 UTC
Updating the app about the information of red,green and orange zones may help the people.
when a person enters any zone ,the app should be able to send notifications to the user in which zone he/she is. 

The section where the app shows who are affected in radius is not shown properly and some of the other details are getting in other details .

**Comment by aravindvnair99** [comment] 2020-05-29 14:18
@arav09 Please check for existing issues before opening a new one. You can close this and proceed there. Duplicate of #71 and #57

**Closed** 2020-05-29 14:20 UTC
