### ISSUE TITLE
In Assist question activity the reset FAB icon is not visible

### ISSUE THREAD

**Issue by beingentangled** [nic-delhi/AarogyaSetu_Android#45] opened 2020-05-26 19:55 UTC
To reproduce:

1.Click blue assist button from homepage
2.Check the button at the right corner without refresh icon.

**Comment by sreejeet** [comment] 2020-05-26 20:31
#7

**Comment by sreejeet** [comment] 2020-05-26 20:33
Duplicate of #7

**Comment by aravindvnair99** [comment] 2020-05-28 17:56
@beingentangled Please check for existing issues before opening a new one. You can close this and proceed there. Duplicate of #7

**Closed** 2020-09-07 14:22 UTC
