### ISSUE TITLE
Small Tweak For UI......Please Insert Swiping Gesture

### ISSUE THREAD

**Issue by balasarapradip** [nic-delhi/AarogyaSetu_Android#296] opened 2020-05-28 15:28 UTC
Please Insert Swiping Gesture To Easily Navigate Between (Your Status),(Media),(COVID Updates) and (E-pass)

**Comment by aravindvnair99** [comment] 2020-05-28 18:25
@balasarapradip Please check for existing issues before opening a new one. You can close this and proceed there. Duplicate of #7

**Closed** 2020-05-28 19:26 UTC
