### ISSUE TITLE
Media should have permission for landscape mode.

### ISSUE THREAD

**Issue by bitactro** [nic-delhi/AarogyaSetu_Android#290] opened 2020-05-28 12:07 UTC
media like youtube embedded videos are hard to watch in full screen even if we press full screen icon given by youtube at bottom right of the video.  Landscape mode should be available for medias at least if we really want people to enjoy spending time watching videos available in media section.

**Comment by aravindvnair99** [comment] 2020-05-28 12:42
@bitactro Please check for existing issues before opening a new one. You can close this and proceed there. Duplicate of #258

**Comment by bitactro** [comment] 2020-05-28 15:52
yes issue closed

**Closed** 2020-05-28 15:52 UTC
