### ISSUE TITLE
Backpress on popup "What do these mean" closes the app instead of popup. 

### ISSUE THREAD

**Issue by beingentangled** [nic-delhi/AarogyaSetu_Android#42] opened 2020-05-26 19:40 UTC
To reproduce :
Click the "?" button to the right side of the text "In your area within radius of"

**Comment by sreejeet** [comment] 2020-05-26 19:43
Please provide steps to reproduce this.

**Comment by Electron-2002** [comment] 2020-05-26 19:44
@beingentangled Maybe add a description about the popup. When does it appear, etc.

**Comment by beingentangled** [comment] 2020-05-26 19:45
Click on the "?" Button to the right side of the "In your area" text on home page.

**Comment by Lav-Hinsu** [comment] 2020-05-26 19:50
how did you compile the app without keystore.Properties ?

**Comment by SharpSreejith** [comment] 2020-05-26 19:50
On back pressed it should go to last activity but it is exiting from the app.

**Comment by sreejeet** [comment] 2020-05-26 19:51
Thank you @beingentangled. Found and reproduced this issue.
This should be a minor feature request / UX upgrade.

**Comment by sreejeet** [comment] 2020-05-26 19:52
@Lav-Hinsu This issue about "keystore.Properties" has already been raised and solved and contained in the README.md file. Please check there.

This issue is unrelated.

**Comment by Lav-Hinsu** [comment] 2020-05-26 19:53
> @Lav-Hinsu This issue about "keystore.Properties" has already been raised and solved and contained in the README.md file. Please check there.
> 
> This issue is unrelated.

please link the issue here. can't find it.

**Comment by sreejeet** [comment] 2020-05-26 19:59
My apologies @Lav-Hinsu , I misinterpreted your issue.
You may raise a new issue for this.

**Comment by Lav-Hinsu** [comment] 2020-05-26 20:01
I did raise an issue, but still haven't received any response from devs.

**Comment by vivekkadu** [comment] 2020-05-27 07:18
This issue is needs to fix , when I have opened the pop up from  testing labs  list state to chosse a state when I have pressed back button it's closed complete app it should close pop up not a app .

**Comment by aravindvnair99** [comment] 2020-05-28 12:53
@beingentangled Please check for existing issues before opening a new one. You can close this and proceed there. Duplicate of #7

**Closed** 2020-09-07 14:21 UTC
