### ISSUE TITLE
[feature] allow manual scroll override of stats display

### ISSUE THREAD

**Issue by aalok-sathe** [nic-delhi/AarogyaSetu_Android#72] opened 2020-05-27 01:23 UTC
Auto scroll data works on its own schedule and its hard to spot the stat you are looking for by waiting for it to show up and last for a fixed duration. The time available to see the stat js proportional to the time needed to wait for it to load.

Allow manual finger scrolling of stats display to override automatic scroll. When finger is lifted and not scrolling anymore, fall back to - automatic.

**Comment by namanrana16** [comment] 2020-05-27 06:42
Can be bundled with #63

**Comment by spandu500** [comment] 2020-05-27 10:46
#31 also mentions this...

**Comment by aravindvnair99** [comment] 2020-05-28 10:24
Duplicate of #31

@aalok-sathe Please check for existing issues before opening a new one. You can close this and proceed there.

**Closed** 2020-05-28 11:03 UTC
