### ISSUE TITLE
After opening FAQs , back button should send you on main screen

### ISSUE THREAD

**Issue by tripathi-swapnil** [nic-delhi/AarogyaSetu_Android#29] opened 2020-05-26 19:24 UTC
After opening FAQs , back button should send you on main screen,

Once you hit back button of mobile, it closes your app, 

Tested in Oneplus6

**Comment by SharpSreejith** [comment] 2020-05-26 19:35
Yes

**Comment by aravindvnair99** [comment] 2020-05-28 12:51
@Anshdesire Please check for existing issues before opening a new one. You can close this and proceed there. Duplicate of #7

**Comment by tripathi-swapnil** [comment] 2021-02-24 10:39
deplicate

**Closed** 2021-02-24 10:39 UTC
