### ISSUE TITLE
updated app and still the reload button on "Assess Again" is the same

### ISSUE THREAD

**Issue by ghost** [nic-delhi/AarogyaSetu_Android#422] opened 2020-06-01 15:45 UTC
I have updated the app from the google play store a few mins ago and i see this reload/refresh button unchanged

Mobile : Mi note 7
Android version : 9 
Miui : 11global (stable)

**Comment by bobobarry** [comment] 2020-06-01 16:07
@BlueTick9000 what did you tell me about this server # Server SSL Keys # configuration ?

**Comment by sreejeet** [comment] 2020-06-01 16:32
Possible duplicate of #7. Please check and confirm.
Was it mentioned anywhere in the update that this issue will be fixed?

**Comment by bobobarry** [comment] 2020-06-01 16:36
I think you are executed on your android studio application

**Closed as completed** 2020-06-01 17:31 UTC
