### ISSUE TITLE
During registration invalid data also taking like invalid name and age.it should accept valid data.

### ISSUE THREAD

**Issue by bipink007** [nic-delhi/AarogyaSetu_Android#220] opened 2020-05-27 16:05 UTC

**Comment by sreejeet** [comment] 2020-05-27 22:47
What inputs did you try?
Which invalid ones got accepted?
Android device model name?
Android version?

**Comment by fuzzy-memory** [comment] 2020-05-28 04:27
Could you please add some details on how to reproduce the problem?

**Comment by bipink007** [comment] 2020-05-28 07:09
Steps to reproduce:-
1)once mobile OTP verification over
2)During first time sign-up I used
full name =.(dot) and age = 0

(Note:-
It is successfully sign-up even after invalid data .
<http://data.name> Name field
is accepting anything special characters, numbers and age also 0 it is
taking)

3) if I did some mistake and I want to go back and only I want to edit age
then undo button in the top right corner if I'm pressing,it is totally
resetting the page but undo should only remove last  mistake.already during
registration reset options is available so both undo and reset has same
functionality in the same page which is not required.

Thanks and Regards
Bipin kumar
Automation quality engineer
Bangalore

**Comment by aravindvnair99** [comment] 2020-05-28 17:30
@bipink007 Please check for existing issues before opening a new one. You can close this and proceed there. Duplicate of #218

**Closed** 2020-05-28 17:57 UTC
