### ISSUE TITLE
Epass FAQ How to apply for epass ?

### ISSUE THREAD

**Issue by sekhar2017** [nic-delhi/AarogyaSetu_Android#240] opened 2020-05-27 19:20 UTC
There is no FAQ for how to apply for epass ? Under epass information faq's .

**Comment by aravindvnair99** [comment] 2020-05-27 19:24
@sekhar2017 Please check for exiting issues before opening a new one. Duplicate of #228

**Comment by sekhar2017** [comment] 2020-10-26 16:25
closed , is duplicate of 228.

**Closed** 2020-10-26 16:25 UTC
