### ISSUE TITLE
Enhanced Readability for `In Your Area Now` Segment

### ISSUE THREAD

**Issue by capturemathan** [nic-delhi/AarogyaSetu_Android#303] opened 2020-05-28 17:07 UTC
`In Your Area Now` segment currently scrolls over information starting from
1. The number of users using the app.
2. The number of users self-assessed within 24 hours
3. **Finally** comes the number of people who have **positive symptoms.**

People have to wait a lot of time for this information to appear and many people wouldn't know of this. A better approach would be to display the **number of affected people first** and then scroll the remaining information (or) have it display in **bold** elsewhere in the app because this is the `Most Important Feature` of the app.

**Comment by aravindvnair99** [comment] 2020-05-28 17:26
@capturemathan Please check for existing issues before opening a new one. You can close this and proceed there. Duplicate of #31

**Closed** 2020-05-29 04:36 UTC
