### ISSUE TITLE
Auto scrolling of data stats is inconsistent and not aligned with the visible space

### ISSUE THREAD

**Issue by namanrana16** [nic-delhi/AarogyaSetu_Android#63] opened 2020-05-26 21:00 UTC
The auto scrolling data stats are not aligned properly to be seen, thus positioning themselves not in the middle but either in top or bottom of the readable space. Also, the space for the stats should be increased for better view and readability.

Device: Redmi 4
Android version: 7.1.2 
MIUI version: MIUI global 11.0.2

**Comment by criticic** [comment] 2020-05-27 03:54
I can also confirm this,
AndroidVersion: 10 (Realme UI V1)
Device: Oppo Realme 3 Pro

**Comment by nitantn** [comment] 2020-05-27 04:28
This issue is seen on many android devices. 
Instead of scrolling, text can be **fade in - fade out** in the same text area, this will help to accommodate entire text within text box.

**Comment by siddhpant** [comment] 2020-05-27 04:32
+1. Can reproduce.

**Comment by spandu500** [comment] 2020-05-27 10:44
#31

**Comment by aravindvnair99** [comment] 2020-05-28 10:24
@namanrana16  Please check for existing issues before opening a new one. You can close this and proceed there. Duplicate of #31

**Closed** 2020-05-28 14:49 UTC
