### ISSUE TITLE
UI mobile issue:- (In splitscreen mode)Text is hidden when clicking on tooltip in header after setup

### ISSUE THREAD

**Issue by ArjitRout** [nic-delhi/AarogyaSetu_Android#137] opened 2020-05-27 06:26 UTC
![E0E6E3D3-7A6F-4B3B-A11B-5B70A1B70D38_1_105_c](https://user-images.githubusercontent.com/37146364/82985124-17a81100-a011-11ea-9a92-278b54678347.jpeg)

UI mobile issue:- (In splitscreen mode)Text is hidden when clicking on tooltip in header after setup

**Comment by aravindvnair99** [comment] 2020-05-28 17:51
@ArjitRout Please check for existing issues before opening a new one. You can close this and proceed there. Duplicate of #7

**Closed** 2020-05-29 06:51 UTC
