### ISSUE TITLE
Age field  should have  should have limit 

### ISSUE THREAD

**Issue by Suresh87QA** [nic-delhi/AarogyaSetu_Android#252] opened 2020-05-28 04:23 UTC
User is able to enter any value in age field - it should have a limit
![Arohya setu 1](https://user-images.githubusercontent.com/64277879/83098689-eee35280-a0c8-11ea-9ad1-25cdae2dbb70.png)

**Comment by shrmakuldeep2311** [comment] 2020-05-28 04:26
That's right

**Comment by sreejeet** [comment] 2020-05-28 07:18
Duplicate of #220

**Comment by aravindvnair99** [comment] 2020-05-28 17:39
@Suresh87QA  Please check for existing issues before opening a new one. You can close this and proceed there. Duplicate of #218

**Comment by Suresh87QA** [comment] 2020-05-29 02:22
Dev working on this issue

**Closed** 2020-05-29 02:21 UTC

**Comment by projjal1** [comment] 2020-05-31 19:04
Aadhar verification should be done via Api to fetch details automatically.
