### ISSUE TITLE
Radius area info text scrolling out of box

### ISSUE THREAD

**Issue by kunjeshn** [nic-delhi/AarogyaSetu_Android#273] opened 2020-05-28 08:40 UTC
The section **'In your area now, within radius of..'** The text scrolling in the box stops at improper positions and the text is not readable..

**Comment by aravindvnair99** [comment] 2020-05-28 10:19
@kunjeshn Please check for existing issues before opening a new one. Duplicate of #246

**Comment by aravindvnair99** [comment] 2020-05-28 10:20
@kunjeshn Please check for existing issues before opening a new one. You can close this and proceed there. Duplicate of #246

**Comment by aravindvnair99** [comment] 2020-05-28 10:23
@kunjeshn Please check for existing issues before opening a new one. You can close this and proceed there. Duplicate of #31

**Closed** 2020-05-28 13:36 UTC
