### ISSUE TITLE
UI issue:- Text overflow issue in Helpline button. Inherited from [https://github.com/nic-delhi/AarogyaSetu_Android/issues/126](126)

### ISSUE THREAD

**Issue by ayushashi11** [nic-delhi/AarogyaSetu_Android#135] opened 2020-05-27 06:25 UTC
(This issue inherits from  [https://github.com/nic-delhi/AarogyaSetu_Android/issues/126](126))
Probably setting android::ellipsize="end" and android::singleLine="true" in the button properties might work.

**Comment by aravindvnair99** [comment] 2020-05-28 17:50
@ayushashi11 Please check for existing issues before opening a new one. You can close this and proceed there. Duplicate of #7

**Closed** 2020-05-29 02:54 UTC
