### ISSUE TITLE
Accepting Negative Age 

### ISSUE THREAD

**Issue by capturemathan** [nic-delhi/AarogyaSetu_Android#302] opened 2020-05-28 16:49 UTC
The app is currently accepting negative age as valid input. Something similar to `android:inputType="number"` would fix this issue :wink:

**Comment by sreejeet** [comment] 2020-05-28 16:54
Duplicate of #220

**Comment by aravindvnair99** [comment] 2020-05-28 17:30
@capturemathan Please check for existing issues before opening a new one. You can close this and proceed there. Duplicate of #218

**Closed** 2020-05-29 04:36 UTC
