### ISSUE TITLE
Pressing back button after playing a video from media exits the app

### ISSUE THREAD

**Issue by pranshu-chandra** [nic-delhi/AarogyaSetu_Android#64] opened 2020-05-26 21:16 UTC
After playing any video on the Media section, pressing the back button should open the Media home page but instead exits the app.

**Comment by developergirl53** [comment] 2020-05-26 21:22
Yes and for entire app the same flow any subsection resultant is only exit happening, back pressed need to be handled.

**Comment by namanrana16** [comment] 2020-05-26 21:24
same problem as #42 and #29

**Comment by sreejeet** [comment] 2020-05-27 06:34
Duplicate of #7

**Comment by aravindvnair99** [comment] 2020-05-28 12:51
@pranshu-chandra Please check for existing issues before opening a new one. You can close this and proceed there. Duplicate of #7

**Closed** 2020-05-28 14:11 UTC
